config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "main#index"

  resources :event_templates

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event_template.rb
class EventTemplate < ApplicationRecord
  validates :name, :youngest, :oldest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/event_templates_controller.rb
class EventTemplatesController < ApplicationController

  def index

  end

  def new
    @template = EventTemplate.new
  end

  def create
    @article = EventTemplate.new(event_template_params)

    if @article.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @template = EventTemplate.find(params[:id])
  end

  def update
    @template = EventTemplate.find(params[:id])
    if @template.update(event_template_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show

  end

  def destroy
    @template.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def event_template_params
    params.require(:event_template).permit(:name, :youngest, :oldest)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_templates_helper.rb
module EventTemplatesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/event_templates/_event_template.erb
<hr>
<h3><%= event_template.name %></h3>
<p>Start from: <%= event_template.youngest %></p>
<p>Until: <%= event_template.oldest %></p>
<p><%= link_to "Edit Template", edit_event_template_path(event_template) %></p>
<hr>

app/views/event_templates/_form.html.erb
<%= form_with model: event_template do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% event_template.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :youngest %><br>
    <%= form.number_field  :youngest, in: 1.0..20.0 %>
    <% event_template.errors.full_messages_for(:youngest).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :oldest %><br>
    <%= form.number_field  :oldest, in: 1.0..20.0 %>
    <% event_template.errors.full_messages_for(:oldest).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/event_templates/edit.html.erb
<h2>Edit Event Template</h2>
<%= render "form", event_template: @template %>

app/views/event_templates/index.html.erb
<h1>Event Templates</h1>

app/views/event_templates/new.html.erb
<h2>New Event Template</h2>

<%= render "form", event_template: @template %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KreastolTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Home</h1>
<hr>

<h2>Events Listing</h2>
<%= link_to "New Template", new_event_template_path %>

<%= render EventTemplate.all %>